import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  subsets: ['latin'], // specify your desired subset(s)
  preload: true, // enable preloading
});

export const metadata = {
  title: "BudgetBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          {children}</body>
      </html>
    </ClerkProvider>
  );
}
